[package]
name = "hivemqtt"
version = "0.1.0"
edition = "2021"
authors = ["Tolumide Shopein <tolumideshopein@gmail.com>"]

[dependencies]
bytes = "1.7.1"
derive_more = { version = "1.0.0", features = ["display"]}