[package]
name = "hivemqtt-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

categories = ["network-programming"]
keywords = ["mqtt", "iot", "mqttv5", "client"]

[lib]
path = "src/lib.rs"


[features]
default = ["logs"]
sync = []
ws = ["dep:websocket"]
logs = ["dep:tracing"]

[dependencies]
bytes = "1.7.1"
derive_more = { version = "1.0.0", features = ["display"]}
thiserror = "=1.0.24"
hivemqtt-macros = { path = "../hivemqtt-macros" }
async-trait = { version = "0.1.83" }
websocket = { version = "0.27.1", optional = true }
tracing = { version = "0.1.41", optional = true }
async-channel = "2.3.1"
futures = "0.3.31"
smol = { version = "2.0.2", features = [] }
tokio = { version = "1.42.0", features = ["macros", "io-util", "net", "sync", "rt"] }