[package]
name = "hivemqtt"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
bytes = "1.7.1"
derive_more = { version = "1.0.0", features = ["display"]}
thiserror = "=1.0.24"