[package]
name = "hivemqtt-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

categories = ["network-programming"]
keywords = ["mqtt", "iot", "mqttv5", "client"]

[lib]
path = "src/lib.rs"

[dependencies]
bytes = "1.7.1"
derive_more = { version = "1.0.0", features = ["display"]}
thiserror = "=1.0.24"
hivemqtt-macros = { path = "../hivemqtt-macros" }
smol = { version = "2.0.2", features = [] }