[package]
name = "hivemqtt-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

categories = ["network-programming"]
keywords = ["mqtt", "iot", "mqttv5", "client"]

[lib]
path = "src/lib.rs"


[features]
default = ["tokio/rt"]
sync = []
async = ["smol", "async-std", "tokio"]
smol = ["dep:smol"]
async-std = ["dep:async-std"]
tokio = ["dep:tokio-stream", "dep:tokio"]
ws = ["dep:websocket"]
logs = ["dep:tracing", "dep:log"]

[dependencies]
bytes = "1.7.1"
derive_more = { version = "1.0.0", features = ["display"]}
thiserror = "=1.0.24"
hivemqtt-macros = { path = "../hivemqtt-macros" }
smol = { version = "2.0.2", features = [], optional = true }
async-std = { version = "1.13.0", optional = true }
tokio-stream = { version = "0.1.17", optional = true }
async-trait = { version = "0.1.83" }
websocket = { version = "0.27.1", optional = true }
tokio = { version = "1.42.0", features = ["macros", "io-util", "net", "sync", "rt"], optional = true }
log = { version = "0.4.22", optional = true }
tracing = { version = "0.1.41", optional = true }